/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.14.4/userguide/multi_project_builds.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

rootProject.name = "java-design-patterns"

include("singleton-classic")
include("singleton-billpugh")
include("singleton-enum")
include("strategy")
include("observer")
include("factory")
include("abstract-factory")
include("builder")
include("adapter")
include("bridge")
include("decorator")
include("composite")
include("facade")
include("flyweight")
include("proxy")
include("prototype")
include("chain-of-responsibility")
include("command")
include("iterator")
include("mediator")
include("memento")
include("state")
include("template-method")
include("visitor")
